### ISSUE TITLE
Including MD5 for Danbooru and Konachan

### ISSUE THREAD

**Issue by DonaldTsang** [CuddleBear92/Hydrus-Presets-and-Scripts#10]
See (for Danbooru):
http://danbooru.donmai.us/posts?tags=md5:c6189d3cf2b3112348e238f397b5c4d4

See (for Konachan):
http://konachan.com/post?tags=md5%3A240d3a9828aa67c3b1edabdd0a91a400

**Comment by CuddleBear92** [comment]
closing this cause its a dupe for #12 that covers more sites
