### ISSUE TITLE
atfbooru not downloading all files

### ISSUE THREAD

**Issue by doomsday53** [CuddleBear92/Hydrus-Presets-and-Scripts#106]
For some reason when I try downloading images from allthefallen.moe / aftbooru.ninja, the number of items in the search is completely different from the number of items that the site claims it has.
![Screenshot 2021-08-31 190541](https://user-images.githubusercontent.com/26168250/131591515-eb103861-4888-4118-9b76-0e3cb3a2867e.png)
![Screenshot 2021-08-31 191053](https://user-images.githubusercontent.com/26168250/131591588-6287e506-9ea1-450c-b116-c246732e3a12.png)
![Screenshot 2021-08-31 190925](https://user-images.githubusercontent.com/26168250/131591516-f7845622-c027-415b-a2d8-2b83ff89746a.png)

**Comment by matjojo** [comment]
Are you maybe logged in on the site? Are there maybe tags limited for users that have pressed "okay" on some banner?

**Comment by doomsday53** [comment]
> Are you maybe logged in on the site? Are there maybe tags limited for users that have pressed "okay" on some banner?

If you mean logged in via hydrus, then no as there is no login parser for the site on hydrus.

**Comment by floogulinc** [comment]
Ko

**Comment by matjojo** [comment]
I meant logged in in your browser, that could explain there being more
files in the browser view.

The other option is that there is some cookie that needs to be copied, you
can do this manually or with Hydrus companion the browser plugin.

I don't know that site so I'm not sure if that is the case here. But try it
at least

**Comment by kotonbu** [comment]
Looks like the parser is running into a page where there is no content since all the posts on that page were removed at the artists request, so Hydrus thinks there is no more content to parse and stops the search.

**Comment by doomsday53** [comment]
> Looks like the parser is running into a page where there is no content since all the posts on that page were removed at the artists request, so Hydrus thinks there is no more content to parse and stops the search.

Wow your right. Pages 6 and up dont have anything just a note. Thank you
