### ISSUE TITLE
Twitter downloader broken, results in 404

### ISSUE THREAD

**Issue by Boy-am-I-Thirsty** [CuddleBear92/Hydrus-Presets-and-Scripts#132]
Ever since yesterday, November 4, none of the twitter links I've sent to hydrus have worked. They all result in "Ignored" with "404" given as the reason. I thought maybe a login is required now, but I've checked how the pages look when not logged into twitter, and they seem to still show the images/videos just fine, so I don't know what the issue is.

**Comment by Zweibach** [comment]
Twitter parser is a default, this issue does not belong on this repo. See https://github.com/hydrusnetwork/hydrus/issues/1268#issuecomment-1304641561
