### ISSUE TITLE
Danbooru doesn't work

### ISSUE THREAD

**Issue by centro39** [CuddleBear92/Hydrus-Presets-and-Scripts#140]
The client stopped downloading from danbooru. The error "Failed to connect" appears.

  File "requests\adapters.py", line 547, in send
requests.exceptions.ConnectionError: ('Connection terminated.', ConnectionResetError(10054, 'Remote host forcibly terminated existing connection', None, 10054, None))

During the processing of the above exception, another exception occurred:

Traceback (last call):
  File "hydrus\client\importing\ClientImportFileSeeds.py", line 1293, in WorkOnURL
    network_job.WaitUntilDone()
  File "hydrus\client\client\networking\ClientNetworkingJobs.py", line 1973, in WaitUntilDone
    raise self._error_exception
  File "hydrus\client\client\networking\ClientNetworkingJobs.py", line 1733, in Start
    raise HydrusExceptions.ConnectionException('Connection failed!' )
hydrus.core.HydrusExceptions.ConnectionException: Failed to connect!

I tried sending cookies through Hydrus companion and it doesn't work.

Works fine with all other sites. I also want to note that Danbooru is not available in my country and I use VPN, can it be a problem?

**Comment by Zweibach** [comment]
> 'Remote host forcibly terminated existing connection'
That says danbooru killed the connection, so yes, it's probably your VPN.
