### ISSUE TITLE
[Request] Hydrus compliant gallery-dl configs

### ISSUE THREAD

**Issue by rewrib** [CuddleBear92/Hydrus-Presets-and-Scripts#153]
I think it would be a great idea to gather our gallery-dl configs here. It is kind of an involved process to figure out, how to setup gallery-dl post processors to parse all the relevant tags, urls and notes in a hydrus compliant manner. So why not share the burden?

**Comment by floogulinc** [comment]
See https://gitgud.io/thatfuckingbird/hydownloader

**Comment by rewrib** [comment]
hydownloader is overkill for my purposes. I have spent hours installing and configuring it, but it still doesn't really work. The tool is amazing, but I just have no luck with it.

Vanilla gallery-dl works fine for me. A lot of Hydrus users seem to use it, too. Even hydownloader users would benefit from crowdsourced gallery-dl configs.

**Comment by Zweibach** [comment]
None of the people involved in this repo are interested in the work required. Go create one for your purposes or fork this one.
