### ISSUE TITLE
Gelbooru parser doesn't parse all pages

### ISSUE THREAD

**Issue by Krejgan** [CuddleBear92/Hydrus-Presets-and-Scripts#155]
Found this bug while trying to download the works of the author known as "coin rand". There are 533 works by this author on Gelbooru, but the parser finds only 335. Judging by the logs, the search stops on page 9 and gives a note that says the following: "The parser found nothing in the document!".

**Comment by Zweibach** [comment]
If there's enough posts hidden, like the given example has a lot of shota which needs a cookie to see, Hydrus figures it hit the end and stops.
