### ISSUE TITLE
InkBunny png doesnt contain login ability

### ISSUE THREAD

**Issue by sashapony** [CuddleBear92/Hydrus-Presets-and-Scripts#166]
As my title says, the InkBunny png doesnt allow for us to login which disables our ability to get content that Requires a login. Please fix?

**Comment by floogulinc** [comment]
Due to some limitations in the hydrus login script system I believe an InkBunny login script is currently impossible. You need to use hydrus companion or similar to send cookies from your browser to hydrus.

**Comment by sashapony** [comment]
Ty so much! I got it working!
