### ISSUE TITLE
Download images posted to subreddits via Imgur

### ISSUE THREAD

**Issue by pokeball99** [CuddleBear92/Hydrus-Presets-and-Scripts#18]
(repost from discord chat)
umm, so i just recalled something that might be helpful, if any of you already haven't made a script or what ever for this already, you can scrape all images off a subreddit with Imgur due to some URL compatibly, so like https://reddit.com/r/pics/ (replace "/r/pics/" with the subbreddit of your choice) and then they all show up on https://imgur.com/r/pics/

**Comment by rachmadaniHaryono** [comment]
i actually try to made this here https://github.com/rachmadaniHaryono/RedditImageGrab, 

see if this meet your requirement

**Comment by CuddleBear92** [comment]
we have a reddit parser that parses all urls. parsers for individually linked sites is still needed for it. should work fine.
