### ISSUE TITLE
Deriving tags from regex of other tags/namespace tags.

### ISSUE THREAD

**Issue by rachmadaniHaryono** [CuddleBear92/Hydrus-Presets-and-Scripts#26]
A file has the tag "filename:big_ugly_name" and we could regex that namespace for another tag.

**Comment by CuddleBear92** [comment]
This isn't in yet. there is no way to use regexes or the sort to use data in other tags like the filename.
This can only be done on import atm. The thoughts on this is to pull such things as the page number from the filename namespace or other things.

The Dev have talked about this one a few times that i know of and is wanted.
