### ISSUE TITLE
Possible optimizations for current gallery downloaders

### ISSUE THREAD

**Issue by DonaldTsang** [CuddleBear92/Hydrus-Presets-and-Scripts#56]
1. Create compatibility layer between Hydrus and the following repos, or
2. Analyze the repos below to find new ways of optimizing Hydrus.
3. Scripts are written in Python (preferably), Ruby, C++, C# or Java.

List of repos as example for future code analysis:
General  
https://github.com/mikf/gallery-dl  
https://github.com/Bionus/imgbrd-grabber  
https://github.com/Xonshiz/comic-dl
Pixiv  
https://github.com/nandaka/pixivUtil2  
https://github.com/vicety/Pixiv-Crawler  
https://github.com/imn5100/pixivDownloader  
https://github.com/xingoxu/pixivDownloader-WPF  
https://github.com/LewisTian/Crawler  
https://github.com/Akaisorani/pixiv-crawler  
dA  
https://github.com/yannDroy/DeviantArtCrawl  
https://github.com/xofred/deviantart-gallery-downloader  
https://github.com/mlvnt/deviantart-scraper  
https://github.com/voyageur/dagr  
fA  
https://github.com/afurry/fadownloader  
https://github.com/recallfuture/FurryDownloader  
https://github.com/BlackDragonF/FurAffinityScraper

**Comment by MsgLosers** [comment]
@DonaldTsang Are you claiming that these 15 one-site crawlers are better optimized than Hydrus Network client?

I'm just curious. I don't understand your Issue request.

**Comment by DonaldTsang** [comment]
@MsgLosers Not necessarily, but there is a possibility that some are better optimized than Hydrus, therfore it is a good idea to do a test run and compare/analyze the results

**Comment by MsgLosers** [comment]
@DonaldTsang I get where you're coming from, but it's not the right time for that. The're already been a huge re-write of the application that does this. Have you tried it yet?

On a second note, this is not the Hydrus Network software github. This is for the parsers/scripts that you can enable on the downloader-software. Not the right github to post your issues. :)

**Comment by DonaldTsang** [comment]
@MsgLosers I am kind of treating this like a notebook because there is no standard documentation (I am talking UML-tier clearity) and that there is a lack of modular improvement or analysis, from downloader to database to external interface.
