### ISSUE TITLE
Current wishlist

### ISSUE THREAD

**Issue by QueenHek** [CuddleBear92/Hydrus-Presets-and-Scripts#69]
This list will only contain features requested through Discord under the #wishlist channel just for my sanity sake.

Items which appeared in the latest feature vote will not be listed here either.

DOWNLOAD SYSTEM PROVEMENTS

- Quick restart of a gallery until it finds known URL/files.
- Retry failed downloads due to a faulty internet connection on a scheduled basis instead of removing them from the queue.
- Publishing a subscription into a gallery-like page e.g show a new page with all the subscriptions syncd in the last hour, each one being a query that needs to be highlighted to be shown
- New type of parser/URL class where instead of returning Gallery, Post, Watcher, or File, it should Return string/tags, or queries e.g. .csv file with tags for the Danbooru parser to query the website with. Should only require to update the .csv to change what's downloaded. **Acknowledged by Devman, waiting for the next iteration of the downloader alongside polishing the idea**
- Default bandwidth rules in the easy import .png
- URL removing in selection by RegEx pattern match, substitution or right-click context menu
- Favorite system for subscriptions so those marked get priority in term of network and processing
- Bandwidth rule that allows to set a "live" limit on data transfer e.g. "Allow only 500kb/s"
- Total progress of sub instead of each query e.g. 50/100 traps in gelbooru query, 7 queries remaining
- UTC timestamp to ISO date text in content parsing
- Extraction of data directly from URL in addition to fetched html/JSON context
- System to be considered busy when syncing a sub so idle maintenance does not trigger. **Acknowledged by Dev**
- Download speed in the gallery downloader to become a rolling average
- Default tag import options to import tags by default
- Reverse download order for gallery downloads

DUPLICATE FILTER IMPROVEMENTS

- Mark the parts of the images with the highest difference
- Sorting of dupes based on user preferences. For example, dupe check first those images with creator:pusc first.
- Color-coded differences e.g color "Higher resolution" in green 
- Make categories persistent so all aspects are always shown
- Floaty window/second screen support e.g have a floating window on the right showcasing the main differences between both files

PERFORMANCE/UNDER THE HOOD IMPROVEMENTS 
- Store/cache the BMPs of both images when using the Dupe Filter so they're not constantly re-rerendered
- XPath support
- Selection of maintenance jobs to be performed during idle time.

QUALITY OF LIFE (TAGGING WORKFLOW) IMPROVEMENTS

- Sort favorite tags by incidence
- Refresh tag recommendation after adding a tag
- Group images by alternates
- Redistributed popups, especially for subscriptions e.g. show errors in a smaller column next to the main one showing progress
- Duplicate page on right-click context menu
- The ability to use things like duration, resolution, system:.. in sorting scheme.
e.g. hair-eyes-duration[low>high]-time importet[high>low] 
- When selecting files, show selected files out of total e.g. 53 out of 197 files in current page
- Quick-add tag(s) to a subscription (from a right-click menu)
- General file entry (as in, inbox) to receive a built-in macro system in which a single keypress may execute multiple functions.
- Higher resolution support with increased max thumbsize and scaler for fonts **Devman has acknowledged the 200px thumbnails**
- More sorting options alongside the current tags/import time
- Zoom improvement
- Custom import actions e.g. import and then do MD5 search on Gelbooru
- Addition of commonly used RegEx
- Key modifiers for the mouse wheel e.g. holding "a" while scrolling downwards applies "anime" tag
- Siblings for namespaces e.g sibling _creator_: to _artist:_ **Acknowledged by Devman**
- Underscores to be used as empty spaces when searching tags in Hydrus e.g _looking__ should give _looking_at_viewer__ and _looking at viewer_ **Acknowledged by Devman**
- HTML parsing being able to transition into API
- Context menu option to add search terms to favorites
- WEBP support **Acknowledged by Devman, awaiting for PIL**
- Mass IQDB or equivalent tag searching
- Auto checking using default tag lookup scripts of recently downloaded/imported files
- Context option to go to an image origin e.g. After downloading images from a watcher and working on them through another page (like system:limit 50), right click on it to open the page that downloaded them (4chan watcher)
- Left-side UI split. "Processing" related buttons would stay on the left side (for example, downloader related options, file import options) while the tags get a new column on the right side.
e.g. https://i.imgur.com/pmcxewN.png (OC by Losers, donut steal)
- Dockable UI
- Tags retain source metadata e.g. manual tagging, Pixiv tagging, AI-generated, X-booru...
- The ability to search for number of tags within a namespace or a simple pattern with wildcards
e.g. number of "character:*anything*" less than 2
- When right clicking and going to open new search pages for each in selection it could show the number of tags selected at the bottom left.
- Send all inboxed files from any query to a new tab with a simple right click on the query.
- Select a favorite tab in the tag manager
- Allow to sort tags in tag manager/selection tags windows/sidebar with similiar namespace sorting sheme options as in sort/collect.
- Tag presentation on thumbnail bottom left
- Truncate the tags or sibling them just for the tag presentation e.g. language:english => eng
- An option/toggle to make anything that goes through the dupe filtered and is not deleted (as in, is a worse image or just straight up deleted) archived in the inbox
- Tagging filter, where using it on a group of files would apply tag A or B depending on what click is used
- Sort certain mimes depending on their inherent qualities e.g JPEG by quality index, audio and vide by bitrate
**v338 added bitrate sorting**
- Rename siblings to "aliases" and parents to "implications"

**Comment by DonaldTsang** [comment]
@QueenHek I see what you did there.

**Comment by QueenHek** [comment]
Sorted the wishlist in four big groups.

As of January posts with an OK on #wishlist have been added. Some big features will not be added until further input from dev or from other users, since there's nearly multi-paragraph ones. I do add them in an extremely brief basis here.

**Comment by DonaldTsang** [comment]
Here is a trifecta of external downloaders that could be useful
- [ ] https://github.com/mikf/gallery-dl
- [ ] https://github.com/Xonshiz/comic-dl
- [ ] https://github.com/JimmXinu/FanFicFare

**Comment by QueenHek** [comment]
Those should be handled by API. Dev probably knows about these.

I won't be adding those to the wishlist since I'm focusing on client-side releases.

**Comment by CuddleBear92** [comment]
Gallery-DL will get a server soon seemingly: https://github.com/mikf/gallery-dl/commit/8662e72bdd80f0158c5d73cccc1d1777f5fbaf33
