### ISSUE TITLE
Hydrus Comic Needs and App Replacements

### ISSUE THREAD

**Issue by CuddleBear92** [CuddleBear92/Hydrus-Presets-and-Scripts#70]
See https://github.com/hydrusnetwork/hydrus/issues/310.

**Comment by DonaldTsang** [comment]
I would add that a https://github.com/evilhero/mylar replacement would be good for torrents

**Comment by Miraihi** [comment]
I personally use Calibre for books and comics, it encompasses all the needs pretty good. Though I'd still prefer using Hydrus as an ultimate piece of software for my whole collection.

**Comment by imtbl** [comment]
See https://github.com/hydrusnetwork/hydrus/issues/310.

@CuddleBear92 I propose we move all still relevant Hydrus proper related issues to the Hydrus issue tracker and close them here.
