### ISSUE TITLE
Issue with downloader

### ISSUE THREAD

**Issue by TyrantTraitor** [CuddleBear92/Hydrus-Presets-and-Scripts#78]
So, I tried to make my own, and when I failed, I came here. But, even with the resources here I still fail to make it function. Hydrus says everything is working fine. Everything looks fine. But, whenever I try to download any tags it doesn't search for anything and just says done. 

So, I was wondering if anyone could help me out and show me how one sets this up. I am fairly tech illiterate but I'd love to learn.

**Comment by CuddleBear92** [comment]
join the discord.
