### ISSUE TITLE
All files completely ignored when using pixiv fanbox downloader.

### ISSUE THREAD

**Issue by BrandonRubadeau** [CuddleBear92/Hydrus-Presets-and-Scripts#81]
I'm not sure why, but when I try to download stuff from the pixiv fanbox downloader every file that it tries to download is ignored. Is there a way to stop the downloader from ignoring them?

**Comment by mserajnik** [comment]
The downloader itself definitely works.

Are you using the latest one for the new fanbox.cc site?
This one: <https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts/blob/6129f688250f7e6271251f1780cc4cff2e2ce938/Download%20System/All-in-Ones/Single-Sites/fanbox-2020.05.18.png>

You need to be logged in on Fanbox and import the login cookies into Hydrus (e.g., using [Hydrus Companion](https://gitgud.io/prkc/hydrus-companion)).

**Comment by imtbl** [comment]
Closed because there has been no further feedback, please reopen if you still have issues with Pixiv.

**Comment by KamillaPup** [comment]
I have this issue like it but only the first image downloads. All other attached images fail. Here is a free post you can test it with.
https://ffxazq.fanbox.cc/posts/3497213
